source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-sse'
gem 'thin'
gem 'rack-cors'

gem 'pubnub', github: 'pubnub/ruby', branch: 'feature/4.0'

gem 'haml'

group :development do
  gem 'pry'
end
